# Generated by Django 4.2.2 on 2023-07-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Neurology', 'Neurology'), ('Dental', 'Dental'), ('Surgery', 'Surgery'), ('Cardiology', 'Cardiology')], max_length=200)),
                ('doctor', models.CharField(choices=[('Mr. Prakash', 'Mr. Prakash'), ('Mrs. Neha', 'Mrs. Neha'), ('Mr. Dewan', 'Mr. Dewan'), ('Mr. Rahul', 'Mr. Rahul')], max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
